site_name: Prudio Documentation

pages:
- [index.md, Home]
- [installation.md, Installation]
- [slash-command.md, "Slash Command <span class='label label-success'>NEW</span>" ]
- [localization.md, Localization]
- [performance.md, Performance & Speed]
- [security.md, Security]
- ['about.md', About]
- [developers/getting-started.md, "Developers", "Getting Started" ]

theme_dir: prudio
favicon: img/favicon.ico
repo_url: https://github.com/PrudioHQ/prudio-docs
repo_name: GitHub
