site_name: Prudio Documentation

pages:
- [index.md, Home]
- [installation.md, Installation]
- [performance.md, Performance & Speed]
- [security.md, Security]
- ['about.md', About]

theme_dir: prudio
favicon: img/favicon.ico
repo_url: https://github.com/asm-products/prudio-docs
repo_name: GitHub
