site_name: Prudio Documentation

pages:
- [index.md, Home]
- [installation.md, Installation]
- [localization.md, Localization]
- [performance.md, Performance & Speed]
- [security.md, Security]
- ['about.md', About]
- [developers/getting_started.md, "Developers", "Getting Started" ]

theme_dir: prudio
favicon: img/favicon.ico
repo_url: https://github.com/asm-products/prudio-docs
repo_name: GitHub
